version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bloomtrack
      - PYTHONPATH=/app
    depends_on:
      - db
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped

  # Database service
  db:
    image: postgis/postgis:14-3.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bloomtrack
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: