apiVersion: v1
kind: Secret
metadata:
  name: bloomtrack-secrets
type: Opaque
data:
  # These are example values - in production, use proper secret management
  # Values are base64 encoded
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGJsb29tdHJhY2stZGI6NTQzMi9ibG9vbXRyYWNr
  redis-url: cmVkaXM6Ly9ibG9vbXRyYWNrLXJlZGlzOjYzNzkvMA==
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=